//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private System.Nullable<decimal> PriceField;
        
        private System.Nullable<System.DateTime> TimestampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBasket")]
public interface IBasket
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasket/Insert", ReplyAction="http://tempuri.org/IBasket/InsertResponse")]
    bool Insert(int userId, int productId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasket/Insert", ReplyAction="http://tempuri.org/IBasket/InsertResponse")]
    System.Threading.Tasks.Task<bool> InsertAsync(int userId, int productId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasket/Remove", ReplyAction="http://tempuri.org/IBasket/RemoveResponse")]
    bool Remove(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasket/Remove", ReplyAction="http://tempuri.org/IBasket/RemoveResponse")]
    System.Threading.Tasks.Task<bool> RemoveAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasket/FindProductsByUser", ReplyAction="http://tempuri.org/IBasket/FindProductsByUserResponse")]
    WCFService.Product[] FindProductsByUser(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasket/FindProductsByUser", ReplyAction="http://tempuri.org/IBasket/FindProductsByUserResponse")]
    System.Threading.Tasks.Task<WCFService.Product[]> FindProductsByUserAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBasketChannel : IBasket, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BasketClient : System.ServiceModel.ClientBase<IBasket>, IBasket
{
    
    public BasketClient()
    {
    }
    
    public BasketClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BasketClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BasketClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BasketClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool Insert(int userId, int productId)
    {
        return base.Channel.Insert(userId, productId);
    }
    
    public System.Threading.Tasks.Task<bool> InsertAsync(int userId, int productId)
    {
        return base.Channel.InsertAsync(userId, productId);
    }
    
    public bool Remove(int id)
    {
        return base.Channel.Remove(id);
    }
    
    public System.Threading.Tasks.Task<bool> RemoveAsync(int id)
    {
        return base.Channel.RemoveAsync(id);
    }
    
    public WCFService.Product[] FindProductsByUser(int id)
    {
        return base.Channel.FindProductsByUser(id);
    }
    
    public System.Threading.Tasks.Task<WCFService.Product[]> FindProductsByUserAsync(int id)
    {
        return base.Channel.FindProductsByUserAsync(id);
    }
}
